[package]
name = "zk_noir"
type = "bin"
authors = ["TrifectaTeam"]
description = "ZK proofs for privacy-preserving features"
version = "0.1.0"

[dependencies]
jwt = { tag = "v0.4.3", git = "https://github.com/zkemail/noir-jwt" }