version: '3.8'

services:
  api:
    image: kidneyweakx/oyster-rewards:latest
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - api_data:/app/data
    networks:
      - oyster_network

networks:
  oyster_network:
    driver: bridge

volumes:
  api_data:
    driver: local 